version: "3.4"

networks:
  flixer.catalog.network:

volumes:
  datafiles:

services:
  flixer_db:
    image: mysql:latest
    ports:
      - "3300:3306"
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    networks:
      - flixer.catalog.network
    environment:
      MYSQL_DATABASE: catalog
      MYSQL_PASSWORD: senha

  flixer.catalog.api:
    build:
      context: .
      dockerfile: ./src/Flixer.Catalog.API/Dockerfile
    depends_on:
      - flixer_db
    networks:
      - flixer.catalog.network
    ports:
      - "5000:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development