version: "3.4"

volumes:
  datafiles:

services:
  flixer.catalog.database:
    image: mysql:latest
    ports:
      - 3300:3306
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: flixer-catalog
        MYSQL_PASSWORD: senha

  flixer.catalog.api:
    build:
      context: .
      dockerfile: ./src/Flixer.Catalog.API/Dockerfile
    depends_on:
      - flixer.catalog.database
    ports:
      - "5000:80"
    restart: always
    environment:
      - DBHOST=flixer.catalog.database
      - ASPNETCORE_ENVIRONMENT=Development
