apiVersion: apps/v1
kind: Deployment
metadata:
  name: flixer-server
  labels:
    app: flixer-server
spec:
  selector:
    matchLabels:
      app: flixer-server
  replicas: 1
  template:
    metadata:
      labels:
        app: flixer-server
    spec:
      containers:
      - name: flixer-server
        image: "jaugustodev/flixer.catalog.docker:latest"

        resources:
          requests:
            cpu: "1" 
            memory: 0.5Gi 
          limits:
            cpu: "2" 
            memory: 1Gi 

        startupProbe: 
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 3
          failureThreshold: 30

        readinessProbe: 
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 3
          failureThreshold: 1

        livenessProbe: 
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1

        envFrom:
          - configMapRef:
              name: flixer-server-env
          - secretRef:
              name: flixer-server-secret