version: "3.8"

networks:
  flixer.catalog.network:

volumes:
  datafiles:

services:
  flixer_db:
    image: mysql:latest
    ports:
      - "3300:3306"
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    networks:
      - flixer.catalog.network
    environment:
      MYSQL_DATABASE: catalog
      MYSQL_ROOT_PASSWORD: senha
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      timeout: 20s
      retries: 10

  flixer.catalog.api:
    build:
      context: .
      dockerfile: ./src/Flixer.Catalog.API/Dockerfile
    depends_on:
      flixer_db:
        condition: service_healthy
    networks:
      - flixer.catalog.network
    ports:
      - "5000:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CatalogDb=Server=flixer_db;Port=3306;Database=catalog;Uid=root;Pwd=senha;

  rabbitmq:
    container_name: adm_flixer_videos_rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=adm_videos
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - 15672:15672
      - 5672:5672