name: flixer-catalog-ci-workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      UNIT_TESTS_FLIXER: ../../Flixer.Catalog.UnitTest/Flixer.Catalog.UnitTest.csproj
      INTEGRATION_TESTS_FLIXER: ../../Flixer.Catalog.IntegrationTests/Flixer.Catalog.IntegrationTests.csproj
      ENDTOEND_TESTS_FLIXER: ../../Flixer.Catalog.EndToEndTests/Flixer.Catalog.EndToEndTests.csproj

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal ${{ env.UNIT_TESTS_FLIXER }}

      - name: Run Integration Tests
        run: dotnet test --no-build --verbosity normal ${{ env.INTEGRATION_TESTS_FLIXER }}

      - name: Run End-to-End Tests
        run: dotnet test --no-build --verbosity normal ${{ env.ENDTOEND_TESTS_FLIXER }}

      - name: Build
        run: dotnet build --no-restore
