name: flixer-catalog-ci-workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  flixer-catalog_ci_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.x"

      - name: Start containers
        run: docker compose -f docker/docker-compose-integration.yml up -d --build

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./src/Flixer.Catalog.Api/Dockerfile
          push: true
          tags: jaugustodev/flixer.catalog.docker:latest